// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Acklann.Templata
{
    static class Vsix
    {
        public const string Id = "Powerbar.VSIX.30e24548-472a-4281-8f38-939c982ab484";
        public const string Name = "Powerbar";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Ackara";
        public const string Tags = "";
    }
}
