// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Acklann.Templata
{
    static class Vsix
    {
        public const string Id = "3c078121-2119-42af-9055-50abb4af5afe";
        public const string Name = "Template Express";
        public const string Description = @"A user file template system.";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Ackara";
        public const string Tags = "";
    }
}
